feat(docs): add ledger docs
fetchai/deprecated-docs pull request #142
Opened 2023-09-19 12:06 UTC by FelixNicolaeBucsa

2023-09-20 08:05 UTC, devjsc requested changes

2023-09-20 08:05 UTC, devjsc commented on pages/guides/ledger/joining-testnet.mdx
I don't want to be committing empty files

2023-09-20 09:21 UTC, FelixNicolaeBucsa commented on pages/guides/ledger/joining-testnet.mdx
Will add content today when I am back

2023-09-21 12:32 UTC, FelixNicolaeBucsa commented on pages/guides/ledger/joining-testnet.mdx
All up-to-date

2023-09-21 12:54 UTC, devjsc commented on pages/concepts/ledger/block-explorer.mdx
> +## Logging in with the ledger nano
everyone one of these sections should have a CTA to a page where it shows them how to do this

2023-09-21 12:55 UTC, devjsc commented on components/products.tsx
>      },
I think the page under concepts should be fetch-network not ledger, or concepts/fetch-network/ledger ../../cosmpy etc

2023-09-21 12:56 UTC, devjsc commented on pages/concepts/ledger/intro.mdx
> +## Mainnet is here!
not a fan of this heading, these concept pages need more thought. Image assets should be included in parts too

2023-09-21 12:56 UTC, FelixNicolaeBucsa commented on components/products.tsx
>      },
Should i move ledger within fetch network?

2023-09-21 12:57 UTC, devjsc commented on pages/concepts/ledger/intro.mdx
> +This documentation covers some of the things you need to know in order to prepare for and develop on this network.
Missing points: 

- what is a bloackchain
 - why do we have one
 - how do we quickly get one running? 
 - what's a testnet, or main net

2023-09-21 12:58 UTC, devjsc commented on pages/concepts/ledger/validators.mdx
> +The Fetch.ai Ledger relies on a set of validators that are responsible for committing new blocks in the blockchain. These validators participate in the consensus protocol by broadcasting votes which
glossary: validators

2023-09-21 12:58 UTC, devjsc commented on pages/concepts/ledger/validators.mdx
> +The Fetch.ai Ledger relies on a set of validators that are responsible for committing new blocks in the blockchain. These validators participate in the consensus protocol by broadcasting votes which
infact this whole opening paragraph is tough, as people will not know what you're on about

2023-09-21 13:00 UTC, devjsc commented on pages/concepts/ledger/validators.mdx
> +If validators double sign, are frequently offline or do not participate in governance, their staked FET (including FET of users that delegated to them) can be slashed. The penalty depends on the seve
talk more about incentives; and link to more information, there must be more?

2023-09-21 13:00 UTC, devjsc commented on pages/concepts/ledger/validators.mdx
> +Validator candidates can bond their own FET and have FET delegated, or staked, to them by token holders. The validators are determined by who has the most stake delegated to them. The top N validator
what does bond mean?

2023-09-21 13:00 UTC, devjsc commented on pages/concepts/ledger/validators.mdx
> +Set up a dedicated validator's website and signal your intention to become a validator on our [Discord ↗️](https://discord.com/invite/fetchai) server. This is important since delegators will want to
is this the right discord link?

2023-09-21 13:02 UTC, devjsc commented on pages/concepts/ledger/validators.mdx
> +Seek legal advice if you intend to run a Validator.
what?

2023-09-21 13:08 UTC, devjsc commented on pages/guides/fetch-network/cosmpy/creating-wallet.mdx
> +# Wallets and private kveys 💸🔐
kveys?

2023-09-21 13:50 UTC, devjsc commented on pages/guides/ledger/cli/delegator.mdx
> +# CLI - Delegator guide
I think we could introduce the section/guide so that when people land on a guide we have something like " You might need to read this, or might have missed this. Reading these will make this page make more sesnse" etc

2023-09-21 13:53 UTC, devjsc commented on pages/guides/ledger/cli/delegator.mdx
> +### How to query the current staking holdings of validators
this guide is a bit dry

2023-09-21 13:54 UTC, devjsc commented on pages/guides/ledger/cli/governance-proposals.mdx
> +**A governance proposal must be submitted to change any attribute of a network**. This could be a simple poll, a software update or a governing parameter change.
I think this could be reworded to be a little more "fluffy"

2023-09-21 13:55 UTC, devjsc commented on pages/guides/ledger/cli/governance-proposals.mdx
> +    ```
To learn more about governance, please see X or Y

2023-09-21 14:16 UTC, FelixNicolaeBucsa commented on pages/concepts/ledger/intro.mdx
> +## Mainnet is here!
Removed this heading and substituted with intro. For images, we can add them when available.

2023-09-21 14:25 UTC, FelixNicolaeBucsa commented on pages/guides/fetch-network/cosmpy/creating-wallet.mdx
> +# Wallets and private kveys 💸🔐
Solved

2023-09-21 14:25 UTC, FelixNicolaeBucsa commented on pages/concepts/ledger/validators.mdx
> +Seek legal advice if you intend to run a Validator.
Removed

2023-09-21 15:22 UTC, FelixNicolaeBucsa commented on pages/concepts/ledger/intro.mdx
> +This documentation covers some of the things you need to know in order to prepare for and develop on this network.
Have reworded and reworked this out by adding info on blockchains, consensus, nodes,  and validators. Also testnet vs mainnet and added a link redirecting users willing to set up a validator node towards the actual guide "How to set up a validator node".

2023-09-21 15:23 UTC, FelixNicolaeBucsa commented on pages/concepts/ledger/validators.mdx
> +The Fetch.ai Ledger relies on a set of validators that are responsible for committing new blocks in the blockchain. These validators participate in the consensus protocol by broadcasting votes which
reworded

2023-09-21 15:33 UTC, FelixNicolaeBucsa commented on pages/concepts/ledger/validators.mdx
> +If validators double sign, are frequently offline or do not participate in governance, their staked FET (including FET of users that delegated to them) can be slashed. The penalty depends on the seve
Added types of incentives for validators

2023-09-21 15:33 UTC, FelixNicolaeBucsa commented on pages/concepts/ledger/validators.mdx
> +Validator candidates can bond their own FET and have FET delegated, or staked, to them by token holders. The validators are determined by who has the most stake delegated to them. The top N validator
in the sense of committed tokens, i.e. bonded

2023-09-21 15:33 UTC, FelixNicolaeBucsa commented on pages/concepts/ledger/validators.mdx
> +Set up a dedicated validator's website and signal your intention to become a validator on our [Discord ↗️](https://discord.com/invite/fetchai) server. This is important since delegators will want to
*substituted with https://discord.gg/fetchai

2023-09-22 13:07 UTC, FelixNicolaeBucsa commented on pages/guides/ledger/cli/delegator.mdx
> +### How to query the current staking holdings of validators
Rewrote content and explained code snippet in a more extensive way

2023-09-26 08:22 UTC, devjsc commented on pages/guides/fetch-network/ledger/block-explorer.mdx
> +import { Callout } from 'nextra/components'
I think this page can be deleted @ejfitzgerald ?

2023-09-26 18:03 UTC, ejfitzgerald commented on pages/guides/fetch-network/ledger/block-explorer.mdx
> +import { Callout } from 'nextra/components'
Yep sure

2023-10-02 07:13 UTC, FelixNicolaeBucsa commented on pages/guides/fetch-network/ledger/block-explorer.mdx
> +import { Callout } from 'nextra/components'
Removed

2023-10-06 13:45 UTC, merged