fix(docs): added check for malicious string in feedback input box
fetchai/deprecated-docs pull request #249
Opened 2023-11-01 06:59 UTC by Shanugoyanka

2023-11-01 08:20 UTC, gautamgambhir97 requested changes

2023-11-01 08:20 UTC, gautamgambhir97 commented on components/feedback.tsx
>                  onClick={handleFeedbackSubmit}
Can we please disable the feedback button if malicious string detected

2023-11-01 08:20 UTC, gautamgambhir97 commented on components/feedback.tsx
> +    }
Suggestion: Can we detect malicious strings in the `onChange` or `onBlur` event handlers? This way, users can identify errors before clicking the submit button. Can we also disable the button if there is no text in the input field and if feedback input is optional , then can we add `Optional` in placeholder ?

2023-11-01 08:29 UTC, Shanugoyanka commented on components/feedback.tsx
>                  onClick={handleFeedbackSubmit}
@gautamgambhir97 malicious string check is for backend, as we are directly storing the data using the API in DB, so that we do not add any kind of sql injection key in here, so whenever the submit is hit, its checks the whole string at once and hence decided whether to hit the API or not

2023-11-01 08:30 UTC, Shanugoyanka commented on components/feedback.tsx
> +    }
@gautamgambhir97 onChange and onBlur logic is same as above reason, Optional placeholder we can place.

2023-11-01 09:05 UTC, gautamgambhir97 commented on components/feedback.tsx
>                  onClick={handleFeedbackSubmit}
@Shanugoyanka  I got this but I was just talking about UX prospective

2023-11-01 15:53 UTC, devjsc commented on components/feedback.tsx
>                  onClick={handleFeedbackSubmit}
Yeah, if we detect malicious let's disable their access - maybe by recording IP and also storing in their cookie?

2023-11-14 13:11 UTC, devjsc commented
Can we resolve the build err please @Shanugoyanka

2023-11-14 13:57 UTC, Shanugoyanka commented
> Can we resolve the build err please @Shanugoyanka

Sure fixing it @devjsc

2023-12-12 07:03 UTC, gautamgambhir97 approved these changes

2023-12-12 07:03 UTC, merged