feat(docs): News Reading System Agentverse
fetchai/deprecated-docs pull request #368
Opened 2024-01-31 13:07 UTC by abhifetch

Creating Agentverse News reading system

2024-02-05 14:14 UTC, FelixNicolaeBucsa submitted a review, later dismissed

2024-02-16 09:16 UTC, devjsc requested changes

2024-02-16 09:16 UTC, devjsc commented on pages/guides/services/field-descriptions-for-deltav.mdx
> +Providing a detailed field description for the `num_rolls` data `Model` is important to correctly execute the service. A well written field description enhances the LLM understanding of the type of *
Need examples of Field Description here: @abhifetch 

Show one which states it needs information from another service. Give maybe 5 examples.

2024-02-16 12:04 UTC, abhifetch commented on pages/guides/services/field-descriptions-for-deltav.mdx
> +Providing a detailed field description for the `num_rolls` data `Model` is important to correctly execute the service. A well written field description enhances the LLM understanding of the type of *
added two more detailed examples. Total 3 examples now and it covers most of the use cases.

2024-02-21 11:36 UTC, devjsc approved these changes

2024-02-21 11:36 UTC, merged