feat: add managed agents section for agentverse docs
fetchai/deprecated-docs pull request #37
Opened 2023-08-15 15:27 UTC by FelixNicolaeBucsa

2023-08-16 13:23 UTC, devjsc commented on pages/concepts/agentverse/managed-agents.md
> +In the **Managed Agents** section you are able to build any type of agent you wish. The benefit for you is that you do not have to carry the hassle of deploying your agents continuously, given that w
merge this into hosting.mdx - hosting.mdx is the example of how we'd like concepts to be written

2023-08-16 13:24 UTC, devjsc requested changes
I think this is unnecessary as covered in hosting.mdx

2023-08-17 11:54 UTC, FelixNicolaeBucsa commented
Ok, no problem

2023-08-17 11:55 UTC, FelixNicolaeBucsa commented on pages/concepts/agentverse/managed-agents.md
> +In the **Managed Agents** section you are able to build any type of agent you wish. The benefit for you is that you do not have to carry the hassle of deploying your agents continuously, given that w
Ok, perfect. Will have a view and edit all Agentverse related docs in the same way

2023-08-18 13:27 UTC, devjsc approved these changes

2023-08-18 13:28 UTC, merged