fix(docs): modified intro in news reading system guide
fetchai/deprecated-docs pull request #430
Opened 2024-02-22 10:04 UTC by FelixNicolaeBucsa

2024-02-22 10:13 UTC, abhifetch submitted a review, later dismissed

2024-02-22 10:18 UTC, devjsc requested changes

2024-02-22 10:18 UTC, devjsc commented on pages/guides/agentverse/utilizing-api-to-build-network-of-task-and-subtask.mdx
> +Sit back, relax, and let DeltaV and the AI Engine bring the top latest headlines to you!
maybe not this line

2024-02-22 10:51 UTC, abhifetch submitted a review, later dismissed

2024-03-08 14:16 UTC, devjsc approved these changes

2024-03-08 14:16 UTC, merged