feat(docs): Api examples
fetchai/deprecated-docs pull request #438
Opened 2024-03-01 13:51 UTC by abhifetch

2024-03-01 15:38 UTC, devjsc requested changes

2024-03-01 15:38 UTC, devjsc commented on pages/apis/ai-engine/chat_api_example.mdx
> +    - An API token (fauna) from Agentverse, which will be used for authentication.
How do we get this, link to the file that describes it.

2024-03-01 15:38 UTC, devjsc commented on pages/apis/ai-engine/chat_api_example.mdx
> +    - The requests library installed. You can install it using pip install requests.
pip install requests

2024-03-01 15:38 UTC, devjsc commented on pages/apis/ai-engine/chat_api_example.mdx
> +    1. Login to agentverse.
agentverse should link to agentverse.ai

2024-03-01 15:38 UTC, devjsc commented on pages/apis/ai-engine/chat_api_example.mdx
> +    5. Copy the fauna’s value and this is your token key.
oh god @ejfitzgerald what is the solution to this?

2024-03-01 15:38 UTC, devjsc commented on pages/apis/ai-engine/chat_api_example.mdx
> +    def normalize_question(question):
might be nice to have type here, so 

`def normalize_question(question : str):`

2024-03-01 15:38 UTC, devjsc commented on pages/apis/ai-engine/chat_api_example.mdx
> +    This function converts questions from a JSON response, identified by the key 'text', into lowercase and removes any punctuation.
Which function? the next one?

2024-03-01 15:38 UTC, devjsc commented on pages/apis/ai-engine/chat_api_example.mdx
> +    This function converts questions from a JSON response, identified by the key 'text', into lowercase and removes any punctuation.
I can't see `.text` am i missing something? 😅

2024-03-01 15:38 UTC, devjsc commented on pages/apis/ai-engine/chat_api_example.mdx
> +    This function is designed to send user's choice back to AI-engine through Chat API, specially in case of user getting options from multiple
Would be great to add an action here such as: 

To understand the flow from Ab to B to C, click here ↗️

2024-03-01 15:38 UTC, devjsc commented on pages/apis/ai-engine/chat_api_example.mdx
> +    This function is designed to send a message from the user to the chat session. This is used to submit user input as part of the chat flow.
```suggestion
    This function to sends a message from the user to the chat session. This is used to submit user input as part of the chat flow.
```

2024-03-01 15:38 UTC, devjsc commented on pages/apis/ai-engine/chat_api_example.mdx
> +    This function checks whether the given key is in UUID (Universal Unique Identifier) format.The function uses a regular expression pattern to match the
```suggestion
    `is_uuid` accepts a key argument, which then verified is the key given is in the correct UUID format. 
```

2024-03-01 15:38 UTC, devjsc commented on pages/apis/ai-engine/chat_api_example.mdx
> +    standard UUID format, which consists of 32 hexadecimal characters split into five groups separated by hyphens (8-4-4-4-12).
```suggestion

```

2024-03-01 15:38 UTC, devjsc commented on pages/apis/ai-engine/chat_api_example.mdx
> +    The function takes the 'key' parameter and returns match object if key is UUID else it returns None.
```suggestion

```

2024-03-01 15:38 UTC, devjsc commented on pages/apis/ai-engine/chat_api_example.mdx
> +    This function is designed to stop the ongoing deltaV chat session.
```suggestion
    `stop_session` posts a request to the chat api to stop the session passed.
```

2024-03-04 10:46 UTC, devjsc commented on pages/apis/ai-engine/chat_api_example.mdx
> +    This function is designed to send user's choice back to AI-engine through Chat API, specially in case of user getting options from multiple
@FelixNicolaeBucsa

2024-03-04 14:10 UTC, FelixNicolaeBucsa commented on pages/examples.mdx
> +            title: "AI-Engine Chat API",
AI Engine

2024-03-04 14:10 UTC, FelixNicolaeBucsa commented on pages/examples/chat-api.mdx
> +- [AI-Engine Chat API guide ↗️](/guides/apis/chat_api_guide)
AI Engine

2024-03-04 14:11 UTC, FelixNicolaeBucsa commented on pages/examples/chat-api.mdx
> +    # define function to normalize questions asked by AI-engine
**D**efine

2024-03-04 14:11 UTC, FelixNicolaeBucsa commented on pages/guides.mdx
> +            title: "AI-Engine Chat API",
AI Engine

2024-03-04 14:11 UTC, FelixNicolaeBucsa commented on pages/guides/_meta.json
> +  "apis": "API"
APIs

2024-03-04 14:11 UTC, FelixNicolaeBucsa commented on pages/guides/apis/_meta.json
> +    "title": "AI-Engine Chat API guide",
AI Engine

2024-03-12 10:07 UTC, closed without merging