feat(docs): added a utils to be used at multiple places to use new he…
fetchai/deprecated-docs pull request #568
Opened 2024-05-09 11:13 UTC by Shanugoyanka

…ader auth wherever needed to call profilio APIs

2024-05-09 15:16 UTC, devjsc commented on pages/api/content-visited.ts
> +    myHeaders.append("Authorization", `Bearer ${accessToken}`);
@Shanugoyanka I updated the quotes, before you were sending effectively a string with quotes inside which we didn't expect on the backend

2024-05-09 15:16 UTC, devjsc submitted a review, later dismissed

2024-05-10 06:46 UTC, gautamgambhir97 requested changes

2024-05-10 06:46 UTC, gautamgambhir97 commented on pages/api/utils/api.ts
> +};
this is already in `fauna.ts` so you can import the function directly from the file

2024-05-10 06:46 UTC, gautamgambhir97 commented on pages/api/utils/api.ts
> +import jwt from "jsonwebtoken";
Please have a look at `jwt.ts` file , we already parsing the jwt token

2024-05-10 06:46 UTC, gautamgambhir97 commented on pages/api/utils/api.ts
> +    }
Refresh mechanism is not working 
![image](https://github.com/fetchai/docs-v2/assets/140384949/87d3a1f5-81db-43cf-ae12-6a979fb366de)

2024-05-10 06:46 UTC, gautamgambhir97 commented on pages/api/utils/api.ts
> +};
if refresh fails to generate new token , please logout the user so that it can create new session to access all services again

2024-05-10 06:58 UTC, Shanugoyanka commented on pages/api/utils/api.ts
> +    }
@gautamgambhir97 I tested thoroughly refresh mechanism is working fine. could you share a video of how to reproduce?

2024-05-10 08:46 UTC, gautamgambhir97 commented on pages/api/utils/api.ts
> +    }
@Shanugoyanka , API is getting 401 and it is not getting refreshed and user is still logged in

[Screencast from 2024-05-10 14-14-01.webm](https://github.com/fetchai/docs-v2/assets/140384949/53362f7f-20c7-448f-ad61-eb9fcf719ebd)

2024-05-10 10:43 UTC, gautamgambhir97 approved these changes

2024-05-10 10:55 UTC, merged