feat(docs): add run agents on agentverse example
fetchai/deprecated-docs pull request #633
Opened 2024-06-24 11:14 UTC by FelixNicolaeBucsa

2024-06-27 09:39 UTC, devjsc submitted a review, later dismissed

2024-07-10 09:10 UTC, devjsc requested changes

2024-07-10 09:10 UTC, devjsc commented on pages/examples/intermediate/running-an-agent-on-agentverse.mdx
> +First of all, navigate towards the [Agentverse ↗️](https://agentverse.ai/), sign in and choose the **My Agents** tab. Here, click on the **+ New Agent** button and choose **Blank Agent**. Provide the
What is the difference between this example and a guide?

2024-07-10 10:32 UTC, FelixNicolaeBucsa commented on pages/examples/intermediate/running-an-agent-on-agentverse.mdx
> +First of all, navigate towards the [Agentverse ↗️](https://agentverse.ai/), sign in and choose the **My Agents** tab. Here, click on the **+ New Agent** button and choose **Blank Agent**. Provide the
I thought this example had to gather ways to create and run agents on Agentverse. I can remove some text around the code in these paragraphs to make it look sharper but let me know what you were thinking for content to be in it

2024-07-10 10:41 UTC, gautamgambhir97 requested changes

2024-07-10 10:41 UTC, gautamgambhir97 commented on pages/examples/intermediate/running-an-agent-on-agentverse.mdx
> +    print(f"Your agent's address is: {agent.address}")
@FelixNicolaeBucsa this should be come after the agent initialisation else the code will through error

2024-07-10 12:06 UTC, FelixNicolaeBucsa commented on pages/examples/intermediate/running-an-agent-on-agentverse.mdx
> +    print(f"Your agent's address is: {agent.address}")
Am fixing it rn

2024-07-10 12:36 UTC, FelixNicolaeBucsa commented on pages/examples/intermediate/running-an-agent-on-agentverse.mdx
> +    print(f"Your agent's address is: {agent.address}")
Solved

2024-07-18 10:13 UTC, merged