fix(docs): addressed feedback in docs
fetchai/deprecated-docs pull request #779
Opened 2024-07-10 15:25 UTC by FelixNicolaeBucsa

This PR addresses the following issues:

- https://github.com/fetchai/docs-v2/issues/774
- https://github.com/fetchai/docs-v2/issues/775
- https://github.com/fetchai/docs-v2/issues/776
- https://github.com/fetchai/docs-v2/issues/777
- https://github.com/fetchai/docs-v2/issues/778

2024-07-10 16:06 UTC, devjsc requested changes

2024-07-10 16:06 UTC, devjsc commented on pages/guides/agents/advanced/message-verification.mdx
> -2. In here, let's create a Python script for this task and name it: `touch message_verification.py`.
Would rather we leave `touch` and we update to support Windows in a future

2024-07-11 07:45 UTC, FelixNicolaeBucsa commented on pages/guides/agents/advanced/message-verification.mdx
> -2. In here, let's create a Python script for this task and name it: `touch message_verification.py`.
Ok will reintegrate `touch` command

2024-07-12 08:39 UTC, devjsc requested changes

2024-07-12 08:39 UTC, devjsc commented on pages/guides/agents/intermediate/storage-function.mdx
> +1. First of all, let's create a Python script, and name it: `touch storage.py`.
```suggestion
1. To start let's create a Python script and name it `storage.py`, we can do this in terminal with `touch storage.py`.
```

2024-07-18 09:34 UTC, devjsc approved these changes

2024-07-18 09:35 UTC, merged