feat(docs) add callout for hyperlinks and rich text in DeltaV resources
fetchai/deprecated-docs pull request #861
Opened 2024-08-14 12:00 UTC by FelixNicolaeBucsa

## Proposed Changes

_Adds callout for info on Rich Text and Hyperlinks in DeltaV._

## Linked Issues

_[Notion Story](https://www.notion.so/04881787f4d648979e3db4d802833afd?v=dac15240fcaa479886ac98d6fece2bed&p=19ddda799a69485a8fb19b161af3ae23&pm=s)_

## Types of changes

_What type of change does this pull request make (put an `x` in the boxes that apply)?_

- [x] Content update.
- [ ] Bug fix (non-breaking change that fixes an issue).
- [x] New feature added (non-breaking change that adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to stop working as expected).
- [x] Something else (e.g., tests, scripts, example, deployment, infrastructure).

## Checklist

_Put an `x` in the boxes that apply:_

- [x] I have read the [CONTRIBUTING](https://github.com/fetchai/docs/blob/main/CONTRIBUTING.md) guide
- [x] Checks and tests pass locally

## Further comments

_[if this is a relatively large or complex change, kick off a discussion by explaining why you chose the solution you did, what alternatives you considered, etc...]_

2024-08-19 13:05 UTC, devjsc requested changes

2024-08-19 13:05 UTC, devjsc commented on pages/concepts/ai-engine/deltav.mdx
> +    <Callout type="info" emoji="ℹ️">
Unnecessary callout as already called out in previous page?

2024-08-19 13:05 UTC, devjsc commented on pages/guides/agents/intermediate/agent-functions.mdx
> +    <Callout type="info" emoji="ℹ️">
Update this to give a link to page on rich text

2024-08-19 13:05 UTC, devjsc commented on pages/guides/agents/intermediate/ai-engine-compatible-agent.mdx
> +    <Callout type="info" emoji="ℹ️">
let's remove this callout

2024-08-19 13:05 UTC, devjsc commented on pages/guides/agents/intermediate/primary-secondary-functions.mdx
> +    <Callout type="info" emoji="ℹ️">
let's remove this callout

2024-08-19 13:05 UTC, devjsc commented on pages/guides/agentverse/agentverse-functions/field-descriptions-for-deltav.mdx
> +    <Callout type="info" emoji="ℹ️">
let's remove this callout

2024-08-19 13:05 UTC, devjsc commented on pages/guides/agentverse/agentverse-functions/registering-agent-services.mdx
> +    <Callout type="info" emoji="ℹ️">
let's remove this callout

2024-08-19 17:20 UTC, FelixNicolaeBucsa reviewed
Have addressed comments. Let me know what you think.

2024-08-19 17:20 UTC, FelixNicolaeBucsa commented on pages/guides/agents/intermediate/ai-engine-compatible-agent.mdx
> +    <Callout type="info" emoji="ℹ️">
Done

2024-08-19 17:20 UTC, FelixNicolaeBucsa commented on pages/guides/agents/intermediate/primary-secondary-functions.mdx
> +    <Callout type="info" emoji="ℹ️">
Done

2024-08-19 17:20 UTC, FelixNicolaeBucsa commented on pages/guides/agentverse/agentverse-functions/field-descriptions-for-deltav.mdx
> +    <Callout type="info" emoji="ℹ️">
Done

2024-08-19 17:20 UTC, FelixNicolaeBucsa commented on pages/guides/agentverse/agentverse-functions/registering-agent-services.mdx
> +    <Callout type="info" emoji="ℹ️">
Done

2024-08-19 17:20 UTC, FelixNicolaeBucsa commented on pages/guides/agents/intermediate/agent-functions.mdx
> +    <Callout type="info" emoji="ℹ️">
Done

2024-08-20 09:23 UTC, abhifetch commented
Can you please update the code with below:

```
import requests
from ai_engine import UAgentResponse, UAgentResponseType

# Define a news content structure using the Model class to represent a news content
class NewsRequest(Model):
    company_name: str

# Create a protocol for the Hugging Face finbert agent
news_protocol = Protocol("Institute News")

async def fetch_symbol(company_name):
    url = f"https://www.alphavantage.co/query?function=SYMBOL_SEARCH&keywords={company_name}&apikey={ALPHA_VANTAGE_API_KEY}"
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()
        # Typically, the best match will be the first item in the bestMatches list
        if data.get('bestMatches') and len(data['bestMatches']) > 0:
            # Return the symbol of the best match
            symbol = data['bestMatches'][0]['1. symbol']
            return symbol
    return 'No Symbol found'

async def analyze_news(company_name):
    """Analyze news sentiment for the company using GNews."""
    url = f"https://gnews.io/api/v4/search?q={company_name}&token={GNEWS_API_KEY}&lang=en"
    response = requests.get(url)
    articles = response.json().get('articles', [])
    
    # Extract URLs and convert them to hyperlinks with titles
    button_list = []
    for article in articles:
        title = article.get("title", "No Title")
        url = article.get("url", "No Url")
        if url != "No Url":
            # Create a clickable button with the title as text
            button_list.append(f'<a href="{url}">{title}</a>')
    
    # Combine buttons into a single string with line breaks
    buttons_combined = '\n'.join(button_list)
    
    return buttons_combined

@news_protocol.on_message(model=NewsRequest, replies=UAgentResponse)
async def on_institute_news_request(ctx: Context, sender: str, msg: NewsRequest):
    ctx.logger.info(msg.company_name)
    symbol = await fetch_symbol(msg.company_name)
    ctx.logger.info(symbol)
    news_content = await analyze_news(symbol)
    ctx.logger.info(news_content)
    await ctx.send(sender, UAgentResponse(message=news_content, type=UAgentResponseType.FINAL))

agent.include(news_protocol)

```

also attach below output image for reference:

![Screenshot 2024-08-20 at 10 21 04](https://github.com/user-attachments/assets/1dd95a9a-3a8e-4d27-89dc-62e63ad6ba1b)

2024-08-22 11:58 UTC, merged