fix: fix on query handler example issue
fetchai/deprecated-docs pull request #923
Opened 2024-08-30 13:21 UTC by gautamgambhir97

## Proposed Changes

_[describe the changes here...]_

## Linked Issues

#920 

## Types of changes

_What type of change does this pull request make (put an `x` in the boxes that apply)?_

- [ ] Content update.
- [ ] Bug fix (non-breaking change that fixes an issue).
- [ ] New feature added (non-breaking change that adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to stop working as expected).
- [ ] Something else (e.g., tests, scripts, example, deployment, infrastructure).

## Checklist

_Put an `x` in the boxes that apply:_

- [ ] I have read the [CONTRIBUTING](https://github.com/fetchai/docs/blob/main/CONTRIBUTING.md) guide
- [ ] Checks and tests pass locally

## Further comments

_[if this is a relatively large or complex change, kick off a discussion by explaining why you chose the solution you did, what alternatives you considered, etc...]_

2024-08-30 13:42 UTC, FelixNicolaeBucsa approved these changes

2024-09-02 07:54 UTC, Archento requested changes
The important bits are the model handling within the `FastAPI` internal server logic which is why we currently need to parse the `Request` object directly.
Please refer to https://github.com/fetchai/uAgents/blob/main/python/examples/16-on-query-proxy/proxy.py#L33-L34
(or simply copy the whole example over into the docs)
Thanks

2024-09-02 12:53 UTC, Archento requested changes
Line 329: imports need to be updated
Line 342: the handler needs an update
Line 366: it's important to change this to the actual FastAPI `Request` model as this contains the whole request of the call
Line 382: imports again
Line 406: again the Request reference

Please check out the whole examples file in the [uagents repo](https://github.com/fetchai/uAgents/blob/main/python/examples/16-on-query-proxy/proxy.py) to make sure that the code does not crash if someone follows these steps one by one.

I think this issue emphasises once again the need for static references to the repo code as we are otherwise chasing a moving target, i.e. every code change in the examples implies an update in the docs.
Although we are trying to keep fundamental changes to the codebase (and therefore changes to the examples) to a minimum it is unfortunately sometimes unavoidable.

2024-09-03 14:10 UTC, Archento approved these changes
Looks good now!

2024-09-06 05:04 UTC, merged